import { getPresentedFindings } from "@/lib/findings/presenter";
import { getFindingsSummary } from "@/lib/findings/summary";

export async function generateFindingsMarkdownReport(): Promise<string> {
  const [summary, presented] = await Promise.all([getFindingsSummary(), getPresentedFindings(15)]);

  const lines: string[] = [];
  lines.push("# Findings Summary Report");
  lines.push("");
  lines.push(`Generated: ${new Date(summary.generatedAt).toISOString()}`);
  lines.push("");
  lines.push("## Overview");
  lines.push("");
  lines.push(`- Total findings: ${summary.total}`);
  lines.push(`- Validated: ${summary.byStage.validated}`);
  lines.push(`- Needs review: ${summary.byStage.needs_review}`);
  lines.push(`- Rejected: ${summary.byStage.rejected}`);
  lines.push("");

  lines.push("## Confidence Distribution");
  lines.push("");
  lines.push(`- High: ${summary.confidenceBands.high}`);
  lines.push(`- Medium: ${summary.confidenceBands.medium}`);
  lines.push(`- Low: ${summary.confidenceBands.low}`);
  lines.push(`- Unknown: ${summary.confidenceBands.unknown}`);
  lines.push("");

  lines.push("## Action Mix");
  lines.push("");
  lines.push(`- file_pr: ${summary.actionCounts.file_pr}`);
  lines.push(`- file_issue: ${summary.actionCounts.file_issue}`);
  lines.push(`- revive_abandoned_pr: ${summary.actionCounts.revive_abandoned_pr}`);
  lines.push(`- needs_human_review: ${summary.actionCounts.needs_human_review}`);
  lines.push(`- reject: ${summary.actionCounts.reject}`);
  lines.push("");

  lines.push("## Top Actionable Findings");
  lines.push("");
  if (summary.topActionable.length === 0) {
    lines.push("- None");
  } else {
    for (const item of summary.topActionable) {
      lines.push(`- [#${item.issueNumber} ${item.issueTitle}](${item.issueUrl})`);
      lines.push(`  - Finding: ${item.findingId}`);
      lines.push(`  - Stage: ${item.stage}`);
      lines.push(`  - Confidence: ${item.confidence ?? "n/a"}`);
      lines.push(`  - Action: ${item.actionNow}`);
    }
  }
  lines.push("");

  lines.push("## Common Blockers");
  lines.push("");
  if (summary.commonBlockers.length === 0) {
    lines.push("- None");
  } else {
    for (const item of summary.commonBlockers) {
      lines.push(`- ${item.blocker}: ${item.count}`);
    }
  }
  lines.push("");

  lines.push("## Recent Findings Snapshot");
  lines.push("");
  const recent = presented.items.slice(0, 10);
  if (recent.length === 0) {
    lines.push("- None");
  } else {
    for (const finding of recent) {
      lines.push(`- [#${finding.issueNumber} ${finding.issueTitle}](${finding.issueUrl})`);
      lines.push(`  - Finding: ${finding.findingId}`);
      lines.push(`  - Stage: ${finding.stage}`);
      lines.push(`  - Confidence: ${finding.confidenceLabel}`);
      lines.push(`  - Action: ${finding.actionNow}`);
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("Generated by repo-analyzer deterministic summary pipeline.");

  return `${lines.join("\n")}\n`;
}
